x-default: &default
  networks:
    - kong-network
x-kong-env: &kong-env
  KONG_DATABASE: postgres
  KONG_PG_HOST: database
  KONG_PG_PASSWORD: kong
  KONG_PASSWORD: kong

networks:
  kong-network:

services:
  httpbin:
    <<: *default
    image: kennethreitz/httpbin:latest
    container_name: httpbin

  database:
    <<: *default
    image: postgres:16
    container_name: database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 30s
      timeout: 30s
      retries: 3
  kong-bootstrap:
    <<: *default
    image: &kong-gateway-image kong/kong-gateway:3.13
    container_name: kong-bootstrap
    depends_on:
      database:
        condition: service_healthy
    command: kong migrations bootstrap
    environment:
      <<: *kong-env
  kong-cp:
    <<: *default
    image: *kong-gateway-image
    container_name: kong-cp
    depends_on:
      kong-bootstrap:
        condition: service_completed_successfully
    ports:
      - 8001:8001
      - 8002:8002
      - 8100:8100
    environment:
      <<: *kong-env
      KONG_ROLE: control_plane
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
      KONG_CLUSTER_LISTEN: 0.0.0.0:8005
      KONG_TELEMETRY_LISTEN: 0.0.0.0:8006
      KONG_STATUS_LISTEN: 0.0.0.0:8100
      KONG_ADMIN_GUI_HOST: http://localhost:8002
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA:-}
      KONG_TRACING_INSTRUMENTATIONS: all
      KONG_TRACING_SAMPLING_RATE: 1.0
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_CLUSTER_CERT: /etc/kong/certs/tls.crt
      KONG_CLUSTER_CERT_KEY: /etc/kong/certs/tls.key
    volumes:
      - ./config/kong/certs:/etc/kong/certs
  kong-dp:
    <<: *default
    image: *kong-gateway-image
    container_name: kong-dp
    depends_on:
      kong-bootstrap:
        condition: service_completed_successfully
    ports:
      - 8000:8000
    environment:
      KONG_ROLE: data_plane
      KONG_DATABASE: off
      KONG_CLUSTER_SERVER_NAME: kong-cluster
      KONG_CLUSTER_CONTROL_PLANE: kong-cp:8005
      KONG_CLUSTER_TELEMETRY_ENDPOINT: kong-cp:8006
      KONG_CLUSTER_TELEMETRY_SERVER_NAME: kong-cp
      KONG_CLUSTER_MTLS: shared
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA:-}
      KONG_TRACING_INSTRUMENTATIONS: all
      KONG_TRACING_SAMPLING_RATE: 1.0
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_CLUSTER_CERT: /etc/kong/certs/tls.crt
      KONG_CLUSTER_CERT_KEY: /etc/kong/certs/tls.key
    volumes:
      - ./config/kong/certs:/etc/kong/certs

  init:
    image: &tempoImage grafana/tempo:2.8.0
    container_name: tempo-init
    user: root
    entrypoint:
      - chown
      - 10001:10001
      - /var/tempo
    networks:
      - kong-network
  memcached:
    <<: *default
    image: memcached:1.6.38
    container_name: memcached
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64m # Set the maximum memory usage
      - MEMCACHED_THREADS=4 # Number of threads to use
  tempo:
    <<: *default
    image: *tempoImage
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - 4317 # gRPC
      - 4318 # HTTP
    depends_on:
      - init

  prometheus:
    <<: *default
    container_name: prometheus
    image: prom/prometheus:v3.4.1
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - 9090

  loki-init:
    image: &lokiImage grafana/loki:3.5.1
    container_name: loki-init
    user: root
    entrypoint:
      - chown
      - 10001:10001
      - /tmp/loki
    networks:
      - kong-network
  loki:
    <<: *default
    container_name: loki
    image: *lokiImage
    command: "-config.file=/etc/loki/loki.yaml"
    environment:
      LOG_CLUSTER_DEPTH: "8"
      LOG_SIM_TH: "0.3"
    volumes:
      - ./config/loki/loki.yaml:/etc/loki/loki.yaml
    ports:
      - 3100
      - 7946
      - 9095
    depends_on:
      - loki-init

  otel-collector:
    <<: *default
    image: otel/opentelemetry-collector-contrib:0.128.0
    container_name: otel-collector
    volumes:
      - ./config/otel-collector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317
      - 4318
      - 8888
      - 8889

  grafana:
    <<: *default
    image: grafana/grafana:12.0.1
    container_name: grafana
    volumes:
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./config/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
    ports:
      - 3000:3000
