x-default: &default
  networks:
    - kong-network

networks:
  kong-network:

services:
  # --- Sample API ---
  api:
    <<: *default
    image: shuheikawamura243/gin-api:1.0.0
    container_name: api
    ports:
      - 8080

  # --- Load Generator ---
  load-generator:
    <<: *default
    image: grafana/k6:1.0.0
    container_name: load-generator
    volumes:
      - ./config/k6:/k6
    command: ["run", "/k6/scenario.js"]
    depends_on:
      - gateway

  # --- Kong Gateway ---
  gateway:
    <<: *default
    image: kong/kong-gateway:3.10.0.2
    container_name: gateway
    ports:
      - 8000:8000 # Gateway
      - 8443:8443
      - 8001:8001 # Admin API
      - 8444:8444
      - 8002:8002 # Admin GUI
      - 8445:8445
      - 8003:8003
      - 8004:8004
    environment:
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA:-}
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_TRACING_INSTRUMENTATIONS: all
      KONG_TRACING_SAMPLING_RATE: 1.0
    volumes:
      - ./config/kong:/kong/declarative

  # --- Tempo ---
  init:
    <<: *default
    image: &tempoImage grafana/tempo:2.8.0
    user: root
    entrypoint:
      - chown
      - 10001:10001
      - /var/tempo
  memcached:
    <<: *default
    image: memcached:1.6.38
    container_name: memcached
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64m # Set the maximum memory usage
      - MEMCACHED_THREADS=4 # Number of threads to use
  tempo:
    <<: *default
    image: *tempoImage
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - 4317 # gRPC
      - 4318 # HTTP
    depends_on:
      - init

  # --- Prometheus ---
  prometheus:
    <<: *default
    image: prom/prometheus:v3.4.1
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - 9090

  # --- Fluent Bit ---
  fluent-bit:
    <<: *default
    image: fluent/fluent-bit:3.1.2
    container_name: fluent-bit
    command: 
      - "--config=/fluent-bit/etc/fluent-bit.yaml"
    volumes:
      - ./config/fluent-bit/fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml

  # --- Loki ---
  loki-init:
    <<: *default
    image: &lokiImage grafana/loki:3.5.1
    user: root
    entrypoint:
      - chown
      - 10001:10001
      - /tmp/loki
  loki:
    <<: *default
    container_name: loki
    image: *lokiImage
    command: "-config.file=/etc/loki/loki.yaml"
    environment:
      LOG_CLUSTER_DEPTH: "8"
      LOG_SIM_TH: "0.3"
    volumes:
      - ./config/loki/loki.yaml:/etc/loki/loki.yaml
    ports:
      - 3100
      - 7946
      - 9095
    depends_on:
      - loki-init

  # --- OpenTelemetry Collector ---
  otel-collector:
    <<: *default
    image: otel/opentelemetry-collector-contrib:0.128.0
    container_name: otel-collector
    volumes:
      - ./config/otel-collector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317
      - 4318
      - 8888
      - 8889

  # --- Grafana ---
  grafana:
    <<: *default
    image: grafana/grafana:12.0.1
    container_name: grafana
    volumes:
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./config/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
    ports:
      - 3000:3000
